### ISSUE TITLE
Sessionize details not correctly setup for CloudgenVerona location

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#191]
Hi @cloudgenverona @andreatosato @MarcoZama @CloudGenVR

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/u4xtzlzt/view/Sessions

**Comment by cloudgenverona** [comment]
Fix it!


Marco Zamana e Andrea Tosato - CloudGen Verona

________________________________
Da: David Rodríguez ***@***.***>
Inviato: domenica 26 marzo 2023 18:45
A: globalazure/communities ***@***.***>
Cc: CloudGen Verona ***@***.***>; Mention ***@***.***>
Oggetto: [globalazure/communities] Sessionize details not correctly setup for CloudgenVerona location (Issue #191)


Hi @cloudgenverona<https://github.com/cloudgenverona> @andreatosato<https://github.com/andreatosato> @MarcoZama<https://github.com/MarcoZama> @CloudGenVR<https://github.com/CloudGenVR>

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/u4xtzlzt/view/Sessions

**Comment by noopman** [comment]
Looks like the API now is accessible! Thanks!
