### ISSUE TITLE
Sessionize details not correctly setup for mugipurwokerto location

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#199]
Hi @agussuparno

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/gru7afqd/view/Sessions

**Comment by agussuparno** [comment]
Hi David,

I already changed the Sessionize settings.
Thanks for your response.

Best regards,

Agus Suparno

________________________________
From: David Rodríguez ***@***.***>
Sent: Sunday, March 26, 2023 11:55 PM
To: globalazure/communities ***@***.***>
Cc: Agus Suparno ***@***.***>; Mention ***@***.***>
Subject: [globalazure/communities] Sessionize details not correctly setup for mugipurwokerto location (Issue #199)


Hi @agussuparno<https://github.com/agussuparno>

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/gru7afqd/view/Sessions

**Comment by davidjrh** [comment]
Hi @agussuparno 

when visiting your endpoint I’m still seeing JavaScript instead of JSON. Can you double check?

https://sessionize.com/api/v2/gru7afqd/view/Sessions

Is the API key “gru7afqd” the correct one?

**Comment by davidjrh** [comment]
Looks good now! Thanks!
